### ISSUE TITLE
copland doesn't work as a search term for map

### ISSUE THREAD

**Issue by Jorge-D-Robles** [popoway/goknights#7]
QC students refer the music building as "Copland" Colloquially. Searching copland on the map yields no results. Add copland as an option for the music building.

**Comment by popoway** [comment]
Proposed fix, to be merged into next release
https://github.com/popoway/goknights/assets/31576265/1b8655a9-3f2b-453b-b2ab-515e35c3277e

**Comment by popoway** [comment]
Fixed in eda1982 and released in prod [v2.3.2](https://github.com/popoway/goknights/releases/tag/v2.3.2)
